export interface Config {
  ERROR_PENALTY: number
  HIGH_LATENCY_PENALTY: number
  HEALTH_SCORE_FALLBACK_THRESHOLD: number
  HEALTH_SCORE_RECOVER_THRESHOLD: number
  MAX_LATENCY_ALLOWED_IN_MS: number
  RECOVER_SCORE_PER_MS: number
  RECOVER_EVALUATION_WAIT_PERIOD_IN_MS: number
}

export const DEFAULT_CONFIG: Config = {
  ERROR_PENALTY: -50,
  HIGH_LATENCY_PENALTY: -20,
  HEALTH_SCORE_FALLBACK_THRESHOLD: -2990,
  HEALTH_SCORE_RECOVER_THRESHOLD: -20,
  MAX_LATENCY_ALLOWED_IN_MS: 500,
  RECOVER_SCORE_PER_MS: 0.005,
  RECOVER_EVALUATION_WAIT_PERIOD_IN_MS: 5000,
}
