export interface Config {
  ERROR_PENALTY: number,
  HIGH_LATENCY_PENALTY: number,
  HEALTH_SCORE_THRESHOLD: number,
  MAX_LATENCY_ALLOWED_IN_MS: number,
  RECOVER_SCORE_PER_SECOND: number,
  RECOVER_EVALUATION_THRESHOLD: number,
  RECOVER_EVALUATION_WAIT_PERIOD_IN_MS: number,
}

export const DEFAULT_CONFIG: Config = {
  ERROR_PENALTY: -50,
  HIGH_LATENCY_PENALTY: -50,
  HEALTH_SCORE_THRESHOLD: -70,
  MAX_LATENCY_ALLOWED_IN_MS: 500,
  RECOVER_SCORE_PER_SECOND: 1,
  RECOVER_EVALUATION_THRESHOLD: -20,
  RECOVER_EVALUATION_WAIT_PERIOD_IN_MS: 5000,
}