# https://taskfile.dev

version: '3'
dotenv: ['.env']

tasks:
  package:login:
    desc: Log into the labrys github package registry to get the patched smart order router. Use a personal access token (classic) with the scope "read:packages" for the password, and your username as the username.
    cmds:
      - npm login --scope=@Labrys-Group --auth-type=legacy --registry=https://npm.pkg.github.com
  build:
    cmds:
      - task: compile:types
      - task: bundle:lambda
  bundle:lambda:
    cmds:
      - cd dist && zip -r lambda.zip . -x '*.map' -x 'bin/*'
  clean:
    cmds:
      - rm -rf dist
  install:
    cmds:
      - npm install
  setup:
    cmds:
      - task: install
      - cp .example.env .env
  compile:types:
    cmds:
      - npm run compile-external-types
      - npm run compile-v3-contract-types
