import { TradeType } from '@pollum-io/sdk-core'
import { CacheMode, ChainId } from '@pollum-io/smart-order-router'
import { CachedRoutesStrategy } from './model/cached-routes-strategy'
import { PairTradeTypeChainId } from './model/pair-trade-type-chain-id'
import { CachedRoutesBucket } from './model/cached-routes-bucket'

/**
 * This is the main configuration for the caching strategies of routes.
 *
 * The keys are generated by calling the `toString` method in the `PairTradeTypeChainId` class,
 * this way we can guarantee the correct format of the key.
 *
 * The values are an object of type `CachedRoutesStrategy`.
 * which receive an array of `CachedRoutesParameters` with the configuration of the buckets.
 */
export const CACHED_ROUTES_CONFIGURATION: Map<string, CachedRoutesStrategy> = new Map([
  /**
   * WETH/USDC - Mainnet
   */
  [
    new PairTradeTypeChainId({
      tokenIn: '0x4200000000000000000000000000000000000006', // WETH
      tokenOut: '0xdBB59E294A93487822d1d7e164609Cd59d396fb5', // USDC
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'WETH/USDC',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
      buckets: [
        new CachedRoutesBucket({ bucket: 0.2, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 1, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 3, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 5, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 8, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 13, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 21, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 34, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 55, cacheMode: CacheMode.Tapcompare }),
      ],
    }),
  ],
  /**
   * USDC/WETH - Mainnet
   */
  [
    new PairTradeTypeChainId({
      tokenIn: '0xdBB59E294A93487822d1d7e164609Cd59d396fb5', // USDC
      tokenOut: '0x4200000000000000000000000000000000000006', // WETH
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'USDC/WETH',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
      buckets: [
        new CachedRoutesBucket({ bucket: 500, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 1_000, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 3_000, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 8_000, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 13_000, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 21_000, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 34_000, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 55_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 89_000, cacheMode: CacheMode.Tapcompare }),
      ],
    }),
  ],
  /**
   * WETH/USDT - Mainnet
   */
  [
    new PairTradeTypeChainId({
      tokenIn: '0x4200000000000000000000000000000000000006', // WETH
      tokenOut: '0x4DFc340487bbec780bA8458e614b732d7226AE8f', // USDT
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'WETH/USDT',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
      buckets: [
        new CachedRoutesBucket({ bucket: 0.2, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 1, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 3, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 5, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 8, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 13, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 21, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 34, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 55, cacheMode: CacheMode.Tapcompare }),
      ],
    }),
  ],
  /**
   * USDT/WETH - Mainnet
   */
  [
    new PairTradeTypeChainId({
      tokenIn: '0x4DFc340487bbec780bA8458e614b732d7226AE8f', // USDT
      tokenOut: '0x4200000000000000000000000000000000000006', // WETH
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'USDT/WETH',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
      buckets: [
        new CachedRoutesBucket({ bucket: 500, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 1_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 3_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 8_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 13_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 21_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 34_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 55_000, cacheMode: CacheMode.Tapcompare }),
        new CachedRoutesBucket({ bucket: 89_000, cacheMode: CacheMode.Tapcompare }),
      ],
    }),
  ],
  [
    new PairTradeTypeChainId({
      tokenIn: '0x4200000000000000000000000000000000000006', // WETH
      tokenOut: '*', // ANY TOKEN
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'WETH/*',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.ROLLUX,
      buckets: [
        new CachedRoutesBucket({ bucket: 0.0025, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 0.006, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 0.025, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 0.06, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 0.25, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 0.6, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 1, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 2, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 3, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 4, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
        new CachedRoutesBucket({ bucket: 5, cacheMode: CacheMode.Tapcompare, withLastNCachedRoutes: 15 }),
      ],
    }),
  ],
])
