name: Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set the correct Node version using nvm
        shell: bash -l {0} 
        run: nvm install
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Unit Tests
        run: npm run test