name: Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      GQL_URL: ${{ secrets.UNI_GRAPHQL_ENDPOINT }}
      GQL_H_ORGN: ${{ secrets.UNI_GRAPHQL_HEADER_ORIGIN }}

    steps:
      # This action should be the first step of your job, and should be loaded on every separate job.
      # If this action is not loaded first, it will not be able to see or block any requests that occured prior to the action running.
      - uses: bullfrogsec/bullfrog@dcde5841b19b7ef693224207a7fdec67fce604db # v0.8.3
        with:
          # List of IPs to allow outbound connections to.
          # By default, only localhost and IPs required for the essential operations of Github Actions are allowed.
          #allowed-ips:

          # List of domains to allow outbound connections to.
          # Wildcards are accepted. For example, if allowing `*.google.com`, this will allow `www.google.com`, `console.cloud.google.com` but not `google.com`.
          # By default, only domains required for essential operations of Github Actions and uploading job summaries are allowed.
          # Refer to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#communication-requirements-for-github-hosted-runners-and-github for additional domains that should be allowed for additional Github Actions features.
          #allowed-domains:

          # The egress policy to enforce. Valid values are `audit` and `block`.
          # Default: audit
          egress-policy: audit
      - name: Checkout Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Run integration tests
        run: npm run test:integ